Update pr messages
is-a-dev/team-docs pull request #5
Opened 2022-10-17 23:57 UTC by WilliamDavidHarrison

2022-10-19 05:55 UTC, WilliamDavidHarrison commented
@phenax What do you think?

2022-10-19 06:00 UTC, phenax commented
LGTM. @is-a-dev/maintainers, can you guys take a look as well?

2022-10-19 06:08 UTC, WilliamDavidHarrison commented
Updated pr-create response as well.

2022-10-22 00:42 UTC, WilliamDavidHarrison commented
@phenax?

2022-10-22 01:43 UTC, TheBotlyNoob requested changes

2022-10-22 01:43 UTC, TheBotlyNoob commented on pr-created.md
> +### FAQ
I don't think we should have a header here, it makes the comment feel a little cluttered for how short it is.

2022-10-22 01:43 UTC, TheBotlyNoob commented on pr-merged.md
> -**Hate it?** Please leave your feedback by [creating an issue](https://github.com/is-a-dev/register/issues/new/choose). We would really like to keep improving this service for other users.
What's your reasoning for removing this?

2022-10-22 01:43 UTC, TheBotlyNoob commented on pr-merged.md
> -<a href="https://www.buymeacoffee.com/phenax" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/default-orange.png" alt="Buy Me A Coffee" height="28" width="119"></a> <a href="https://li
ditto here

2022-10-22 01:43 UTC, TheBotlyNoob commented on pr-merged.md
> +If your domain points to a server you own, add your-domain.is-a.dev to your domain configuration. For HTTPS, you will have to configure an SSL certificate to allow the new subdomain to work ([here's
small nitpick, maybe we should use [https://get.dev/#:~:text=The%20.dev%20top%2Dlevel%20domain%20is%20included%20on%20the%20HSTS%20preload%20list%2C%20making%20HTTPS%20required%20on%20all%20connections%20to%20.dev%20websites%20and%20pages%20without%20needing%20individual%20HSTS%20registration%20or%20configuration.%20Security%20is%20built%20in.](https://get.dev/#:~:text=The%20.dev%20top%2Dlevel%20domain%20is%20included%20on%20the%20HSTS%20preload%20list%2C%20making%20HTTPS%20required%20on%20all%20connections%20to%20.dev%20websites%20and%20pages%20without%20needing%20individual%20HSTS%20registration%20or%20configuration.%20Security%20is%20built%20in.) instead because it doesn't hardcode the language.

2022-10-22 04:01 UTC, WilliamDavidHarrison commented on pr-merged.md
> +If your domain points to a server you own, add your-domain.is-a.dev to your domain configuration. For HTTPS, you will have to configure an SSL certificate to allow the new subdomain to work ([here's
Changed here: c808124dd41e0498094d3fe3ba9bc648ce1a3d73

2022-10-22 04:04 UTC, WilliamDavidHarrison commented on pr-created.md
> +### FAQ
Changed here: 6817504a9785841e38abceb547e554c622ca6aaf

2022-10-22 04:05 UTC, WilliamDavidHarrison commented on pr-merged.md
> -**Hate it?** Please leave your feedback by [creating an issue](https://github.com/is-a-dev/register/issues/new/choose). We would really like to keep improving this service for other users.
I think personally it just seems a bit childish, I can re-add it if you want.

2022-10-22 04:20 UTC, TheBotlyNoob commented on pr-merged.md
> -**Hate it?** Please leave your feedback by [creating an issue](https://github.com/is-a-dev/register/issues/new/choose). We would really like to keep improving this service for other users.
I don't really mind, I just wanted to see your reasoning.

2022-10-22 04:21 UTC, TheBotlyNoob approved these changes
:+1: LGTM

2022-10-22 04:36 UTC, WilliamDavidHarrison commented
Updated pr-review file.

2022-11-06 00:11 UTC, WilliamDavidHarrison commented
@phenax can you merge now?

2022-11-08 12:48 UTC, merged